// ============================================================
//  ESCOM — Sistema de Servicio Social
//  Datos en duro: Carta Compromiso por alumno
// ============================================================

export const ALUMNOS_CARTA = [
  {
    id: 1,
    nombre: "García López Juan Carlos",
    boleta: "2021630412",
    carrera: "Ingeniería en Sistemas Computacionales",
    carreraCorta: "ISC",
    oferta: "Sistema Web para Control Escolar",
    empresa: "ESCOM - IPN",
    asesorExterno: "Ing. Roberto Morales",
    fechaInicio: "2026-02-01",
    cartaCompromiso: {
      enviada: false,
      archivo: null,
      nombreArchivo: null,
      fechaEnvio: null,
    },
  },
  {
    id: 2,
    nombre: "Ramírez Torres Ana Sofía",
    boleta: "2022630187",
    carrera: "Ingeniería en Inteligencia Artificial",
    carreraCorta: "IA",
    oferta: "Modelo Predictivo con ML",
    empresa: "DataSoft S.A. de C.V.",
    asesorExterno: "Dr. Felipe Gutiérrez",
    fechaInicio: "2026-02-15",
    cartaCompromiso: {
      enviada: true,
      archivo: null,
      nombreArchivo: "carta_compromiso_ramirez.pdf",
      fechaEnvio: "2026-03-05T10:30:00",
    },
  },
  {
    id: 3,
    nombre: "Mendoza Vargas Luis Alberto",
    boleta: "2020630098",
    carrera: "Ingeniería en Sistemas Computacionales",
    carreraCorta: "ISC",
    oferta: "App móvil para logística",
    empresa: "Logística Express MX",
    asesorExterno: "M.C. Sandra Pérez",
    fechaInicio: "2026-01-20",
    cartaCompromiso: {
      enviada: true,
      archivo: null,
      nombreArchivo: "carta_compromiso_mendoza.pdf",
      fechaEnvio: "2026-02-28T09:15:00",
    },
  },
  {
    id: 4,
    nombre: "Herrera Sánchez Valeria",
    boleta: "2023630301",
    carrera: "Ingeniería en Sistemas Computacionales",
    carreraCorta: "ISC",
    oferta: "Sistema de Inventario en la Nube",
    empresa: "CloudBase Technologies",
    asesorExterno: "Ing. Marco Jiménez",
    fechaInicio: "2026-03-01",
    cartaCompromiso: {
      enviada: false,
      archivo: null,
      nombreArchivo: null,
      fechaEnvio: null,
    },
  },
  {
    id: 5,
    nombre: "Cruz Domínguez Pedro Emmanuel",
    boleta: "2021630577",
    carrera: "Ingeniería en Inteligencia Artificial",
    carreraCorta: "IA",
    oferta: "Chatbot de atención al cliente",
    empresa: "TechServ S.A.",
    asesorExterno: "Dr. Arturo Vázquez",
    fechaInicio: "2026-02-10",
    cartaCompromiso: {
      enviada: false,
      archivo: null,
      nombreArchivo: null,
      fechaEnvio: null,
    },
  },
  {
    id: 6,
    nombre: "López Fuentes María Fernanda",
    boleta: "2022630254",
    carrera: "Ingeniería en Sistemas Computacionales",
    carreraCorta: "ISC",
    oferta: "Portal de trámites digitales",
    empresa: "GobiernoDigital CDMX",
    asesorExterno: "Lic. Carmen Ruiz",
    fechaInicio: "2026-01-15",
    cartaCompromiso: {
      enviada: true,
      archivo: null,
      nombreArchivo: "carta_compromiso_lopez_fuentes.pdf",
      fechaEnvio: "2026-02-20T14:45:00",
    },
  },
  {
    id: 7,
    nombre: "Torres Aguirre Carlos Iván",
    boleta: "2020630411",
    carrera: "Ingeniería en Inteligencia Artificial",
    carreraCorta: "IA",
    oferta: "Reconocimiento de imágenes médicas",
    empresa: "MedTech Innovación",
    asesorExterno: "Dr. Ramón Castillo",
    fechaInicio: "2026-02-01",
    cartaCompromiso: {
      enviada: false,
      archivo: null,
      nombreArchivo: null,
      fechaEnvio: null,
    },
  },
  {
    id: 8,
    nombre: "Flores Castillo Diana Paola",
    boleta: "2023630089",
    carrera: "Ingeniería en Sistemas Computacionales",
    carreraCorta: "ISC",
    oferta: "Automatización de procesos con RPA",
    empresa: "Automatize Corp.",
    asesorExterno: "M.C. Juan Espinoza",
    fechaInicio: "2026-03-10",
    cartaCompromiso: {
      enviada: true,
      archivo: null,
      nombreArchivo: "carta_compromiso_flores.pdf",
      fechaEnvio: "2026-03-18T11:00:00",
    },
  },
];
